CREATE TABLE reservation (
    id INT AUTO_INCREMENT PRIMARY KEY,
    roomId INT NULL,
    name VARCHAR(400) NOT NULL,
    orgaName VARCHAR(150) NOT NULL,
    orgaMail VARCHAR(200) NOT NULL,
    orgaTel VARCHAR(10) NOT NULL,
    hostName VARCHAR(500) NOT NULL,
    guests INT NOT NULL ,
    date DATE NOT NULL,
    startHour VARCHAR(5) NOT NULL,
    endHour VARCHAR(5) NOT NULL,
    roomConfiguration VARCHAR(30) NOT NULL,
    configurationSize INT,
    configurationQuantity INT NULL,
    roomConfigurationPrecision VARCHAR(400),
    hostTable BOOLEAN NOT NULL DEFAULT TRUE,
    paperboard INT NOT NULL DEFAULT 0,
    chairSup INT NOT NULL DEFAULT 0 ,
    tableSup INT NOT NULL DEFAULT 0 ,
    pen BOOLEAN NOT NULL DEFAULT FALSE,
    paper BOOLEAN NOT NULL DEFAULT FALSE,
    scissors BOOLEAN NOT NULL DEFAULT FALSE,
    scotch BOOLEAN NOT NULL DEFAULT FALSE,
    postItXl INT NOT NULL DEFAULT 0,
    paperA1 BOOLEAN NOT NULL DEFAULT FALSE,
    blocNote BOOLEAN NOT NULL DEFAULT FALSE,
    gomette BOOLEAN NOT NULL DEFAULT FALSE,
    postIt BOOLEAN NOT NULL DEFAULT FALSE,
    coffeeGroom INT NOT NULL DEFAULT 0,
    meal INT NOT NULL DEFAULT 0,
    mealPrecision VARCHAR(400),
    morningCoffee INT NOT NULL DEFAULT 0,
    afternoonCoffee INT NOT NULL DEFAULT 0,
    coktail INT NOT NULL DEFAULT 0,
    vegetarian INT NOT NULL DEFAULT 0,
    glutenFree INT NOT NULL DEFAULT 0,

    FOREIGN KEY (roomId) REFERENCES room(id),
    CONSTRAINT guestNotZero CHECK (guests>0),
    CONSTRAINT chairSupLimit CHECK (chairSup<=6),
    CONSTRAINT tableSupLimit CHECK (tableSup<=4)
);

